#-----------------------------------------------------------------------
# Provider region
#-----------------------------------------------------------------------
variable "region" {
  description = "AWS Region for Genesis DevOps School"
  type        = string
  default     = "us-east-1"
}

#-----------------------------------------------------------------------
# Profile
#-----------------------------------------------------------------------
variable "profile" {
  description = "Profile for Genesis DevOps School"
  type        = string
  default     = "genesis"
}

#-----------------------------------------------------------------------
# Project name
#-----------------------------------------------------------------------
variable "project" {
  description = "The project name"
  type        = string
  default     = "Genesis"
}

#-----------------------------------------------------------------------
# The project Environment
#-----------------------------------------------------------------------
variable "env" {
  description = "The Environment for Genesis DevOps School"
  type        = string
  default     = "dev"
}

#-----------------------------------------------------------------------
# VPC
#-----------------------------------------------------------------------
variable "vpc_cidr" {
  description = "IPv4 CIDR for Genesis DevOps School"
  default     = "10.10.0.0/16"
}

variable "public_subnet_cidrs" {
  description = "CIDRs forpublic subnets"
  type        = list(string)
  default = [
    "10.10.1.0/24",
    "10.10.2.0/24",
  ]
}

variable "privet_subnet_cidrs" {
  description = "CIDRs for privet subnets"
  type        = list(string)
  default = [
    "10.10.11.0/24",
    "10.10.12.0/24",
  ]
}

# variable "database_subnet_cidrs" {
#   description = "CIDRs for database subnets"
#   type        = list(string)
#   default = [
#     "10.10.21.0/24",
#     "10.10.22.0/24",
#   ]
# }

variable "enabled_dns_support" {
  type        = bool
  description = "enabling dns support"
  default     = true
}

variable "enabled_dns_hostnames" {
  type        = bool
  description = "enabling dns hostnames"
  default     = true
}

#-----------------------------------------------------------------------
# SSH
#-----------------------------------------------------------------------
variable "ssh_user_name" {
  description = "The user name for ssh"
  type        = string
  default     = ""
}

variable "ssh_key" {
  description = "Key-pair generated by Terraform"
  type        = map(any)
  default = {
    "install" = false
    "name"    = ""
  }
}

#-----------------------------------------------------------------------
# EC2
#-----------------------------------------------------------------------
variable "instance_type" {
  description = "Instance Type for application instance"
  type        = map(any)
  default = {
    "app" = "t2.micro"
  }
}

variable "vm_node_count" {
  description = "Count app instance"
  default     = 1
}

variable "host_name" {
  description = "Count app instance"
  default     = "app"
}

#-----------------------------------------------------------------------
# Security group
#-----------------------------------------------------------------------
variable "allow_port_list" {
  description = "List of Ports to open for all groups"
  type        = map(any)
  default = {
    "app" = ["5000"]
    "alb" = ["5000", "80"]
    "rds" = ["3306"]
  }
}

variable "ssh_cidr" {
  description = "Private IP for ssh"
  type        = string
  default     = ""
}

#-----------------------------------------------------------------------
# RDS
#-----------------------------------------------------------------------
variable "rds" {
  description = "Variables for RDS: name, username, password, port"
  type        = map(any)
  default = {
    "create"      = true
    "create_pass" = false
    "db_name"     = "student"
    "db_user"     = "devops"
    "db_pass"     = "devops"
    "db_port"     = "3306"
  }
}

#-----------------------------------------------------------------------
# Tags
#-----------------------------------------------------------------------
variable "common_tags" {
  description = "Common Tags to apply to all resources"
  type        = map(any)
  default = {
    Owner = ""
  }
}

#-----------------------------------------------------------------------
# Provisioner Ansible
#-----------------------------------------------------------------------
variable "ansible" {
  description = "Provisioning ansible for create app on the server"
  type        = bool
  default     = false
}