---
- name: update the apt package index and install packages to allow apt to use a repository over HTTPS
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ docker.apt_list }}"

- name: add Dockers official GPG key
  apt_key:
    url: "{{ docker.gpg_key }}"
    keyring: "{{ docker.keyring }}"
    state: present

- name: set up the stable repository
  shell: |
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by={{ docker.keyring }}] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee {{ docker.source_file }} > /dev/null

- name: install Docker Engine
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ docker.packages }}"
  changed_when: true

- name:  run and enable Docker
  systemd:
    name: "docker"
    state: started
    enabled: yes

- name: install Docker-Compose
  get_url:
    url : "{{ docker_compose.url }}"
    dest: "{{ docker_compose.bin }}"
    mode: '0755'
    force: yes

- name: check docker version and docker-compose
  shell: |
    /usr/bin/docker version
    /usr/local/bin/docker-compose --version
  register: docker_check

- name: debug docker
  ansible.builtin.debug:
    msg: "{{ docker_check.stdout.split('\n') }}"